#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных. (WELL DONE)
#  - Указать порт приложения. (WELL DONE)
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  application:
    name: bankcards
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: kali
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true