--liquibase formatted sql
    
--changeset Sashacurry:create-users-table
--comment: Создание таблицы Users
CREATE TABLE users(
    id_user int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname varchar(20) NOT NULL,
    midname varchar(20) NOT NULL,
    lastname varchar(20) NOT NULL,
    login varchar(30) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,
    roles varchar(100) NOT NULL
);

--rollback DROP TABLE users;