--liquibase formatted sql
    
--changeset SashaCurry:create-users-table
--comment: Создание таблицы Users
CREATE TABLE users(
    id_user int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    login varchar(30) NOT NULL UNIQUE,
    password varchar(100) NOT NULL,
    roles varchar(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

--rollback DROP TABLE users;